# Generated by Django 6.0.1 on 2026-02-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Sensor Name")),
                (
                    "sensor_type",
                    models.CharField(max_length=50, verbose_name="Sensor Type"),
                ),
                ("value", models.FloatField(verbose_name="Current Value")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.device",
                        verbose_name="Device",
                    ),
                ),
            ],
        ),
    ]
